Repository stackabletech/hbase-operator, pull requests merged in 2023-11, with the labels that each got.

#416 Document the hbase-operator-tools contained in the HBase image
  docs/modules/hbase/examples/usage-guide/hbck2-job.yaml
  docs/modules/hbase/pages/usage-guide/operations/cluster-operations.adoc
Labels: customer-request, area/documentation

#415 Add documentation on supported compression algorithms
  docs/modules/hbase/pages/usage-guide/compression.adoc
  docs/modules/hbase/partials/nav.adoc
Labels: release/2023-11

#418 Disable reverse DNS lookup for RegionServers
  CHANGELOG.md
  rust/crd/src/lib.rs
Labels: changelog/highlight, customer-request

#421 docs: Add listener-operator where missing
  docs/modules/hbase/examples/getting_started/getting_started.sh
  docs/modules/hbase/examples/getting_started/getting_started.sh.j2
  docs/modules/hbase/examples/getting_started/hbase.yaml.j2
  docs/modules/hbase/examples/getting_started/hdfs.yaml.j2
  docs/modules/hbase/examples/getting_started/install_output.txt
  docs/modules/hbase/examples/getting_started/install_output.txt.j2
  docs/modules/hbase/pages/getting_started/installation.adoc
  docs/templating_vars.yaml
Labels: area/documentation
